service: x-files-api
frameworkVersion: "3"

plugins:
  - serverless-offline
  - serverless-aws-static-file-handler/plugins/BinaryMediaTypes
  - serverless-domain-manager

custom:
  apiGateway:
    binaryMediaTypes:
      - image/png
      - image/jpeg
      - "*/*"
  customDomain:
    domainName: x-files.dev
    stage: dev
    certificateName: x-files.dev
    createRoute53Record: true
    createRoute53IPv6Record: true
    endpointType: REGIONAL
    securityPolicy: tls_1_2
    apiType: rest
    autoDomain: false

provider:
  name: aws
  stage: dev
  region: us-west-2
  runtime: nodejs16.x
  stackName: x-files-api
  stackTags:
    Name: x-files-api
  tags:
    Name: x-files-api

functions:
  html:
    handler: dist/server.html
    events:
      - http:
          path: /
          method: get
  binary:
    handler: dist/server.binary
    events:
      - http:
          path: /binary/{foo+}
          method: get
  graphql:
    handler: dist/server.graphql
    events:
      - http:
          path: /graphql
          method: post
          cors: true
  graphiql:
    handler: dist/server.graphiql
    events:
      - http:
          path: /graphql
          method: get
          cors: true
