service: x-files-api
frameworkVersion: "3"

provider:
  name: aws
  stage: dev
  region: us-west-2
  runtime: nodejs16.x
  stackName: x-files-api

functions:
  graphql:
    handler: dist/server.graphqlHandler
    events:
      - http:
          path: /graphql
          method: post
          cors: true
      - http:
          path: /graphql
          method: get
          cors: true
