# Simple workflow to build the server and deploy it to AWS Elastic Beanstalk
name: Build & Deploy

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
    
    env:
      VERSION_LABEL: ${{ github.ref_name }}-${{ github.sha }}
      
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          
      - name: Install Dependencies
        run: npm ci
      
      - name: Production NPM Build
        run: npm run build
        
      - name: Generate Artifact
        run: zip -r $VERSION_LABEL.zip . -x "*.git*"
        
      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with: 
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: X-Files-API
          environment_name: X-Files-API-Environment
          version_label: ${{ env.VERSION_LABEL }}
          region: us-west-2
          deployment_package: ${{ env.VERSION_LABEL }}.zip
